// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: AssetData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface AssetData {
  /** user account */
  account: string;
  /** currency. USD, HKD, etc. */
  currency: string;
  /** Securities Category C: (Commodities Futures), S: (Securities Stocks) */
  segType: string;
  /** available funds, overnight liquidity */
  availableFunds: number;
  /** excess liquidity, used to represent intraday risk value. */
  excessLiquidity: number;
  /** Total Assets (Net Liquidation Value) */
  netLiquidation: number;
  /** Equity with loan value (asset with loan value) - Securities Segment: Cash Value + Stock Value - Futures Segment: Cash Value - Maintenance Margin */
  equityWithLoan: number;
  /** buying power. An estimation of how many more dollars you can buy in stock assets. Only apply to stock segment */
  buyingPower: number;
  /** Cash amount. Sum of current cash balances in all currencies */
  cashBalance: number;
  /** total value of securities */
  grossPositionValue: number;
  /** initial margin requirement */
  initMarginReq: number;
  /** maintenance margin requirement */
  maintMarginReq: number;
  timestamp: number;
}

function createBaseAssetData(): AssetData {
  return {
    account: "",
    currency: "",
    segType: "",
    availableFunds: 0,
    excessLiquidity: 0,
    netLiquidation: 0,
    equityWithLoan: 0,
    buyingPower: 0,
    cashBalance: 0,
    grossPositionValue: 0,
    initMarginReq: 0,
    maintMarginReq: 0,
    timestamp: 0,
  };
}

export const AssetData: MessageFns<AssetData> = {
  encode(message: AssetData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.account !== "") {
      writer.uint32(10).string(message.account);
    }
    if (message.currency !== "") {
      writer.uint32(18).string(message.currency);
    }
    if (message.segType !== "") {
      writer.uint32(26).string(message.segType);
    }
    if (message.availableFunds !== 0) {
      writer.uint32(33).double(message.availableFunds);
    }
    if (message.excessLiquidity !== 0) {
      writer.uint32(41).double(message.excessLiquidity);
    }
    if (message.netLiquidation !== 0) {
      writer.uint32(49).double(message.netLiquidation);
    }
    if (message.equityWithLoan !== 0) {
      writer.uint32(57).double(message.equityWithLoan);
    }
    if (message.buyingPower !== 0) {
      writer.uint32(65).double(message.buyingPower);
    }
    if (message.cashBalance !== 0) {
      writer.uint32(73).double(message.cashBalance);
    }
    if (message.grossPositionValue !== 0) {
      writer.uint32(81).double(message.grossPositionValue);
    }
    if (message.initMarginReq !== 0) {
      writer.uint32(89).double(message.initMarginReq);
    }
    if (message.maintMarginReq !== 0) {
      writer.uint32(97).double(message.maintMarginReq);
    }
    if (message.timestamp !== 0) {
      writer.uint32(104).uint64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssetData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.account = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.segType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.availableFunds = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.excessLiquidity = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.netLiquidation = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.equityWithLoan = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.buyingPower = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 73) {
            break;
          }

          message.cashBalance = reader.double();
          continue;
        }
        case 10: {
          if (tag !== 81) {
            break;
          }

          message.grossPositionValue = reader.double();
          continue;
        }
        case 11: {
          if (tag !== 89) {
            break;
          }

          message.initMarginReq = reader.double();
          continue;
        }
        case 12: {
          if (tag !== 97) {
            break;
          }

          message.maintMarginReq = reader.double();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<AssetData>, I>>(base?: I): AssetData {
    return AssetData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AssetData>, I>>(object: I): AssetData {
    const message = createBaseAssetData();
    message.account = object.account ?? "";
    message.currency = object.currency ?? "";
    message.segType = object.segType ?? "";
    message.availableFunds = object.availableFunds ?? 0;
    message.excessLiquidity = object.excessLiquidity ?? 0;
    message.netLiquidation = object.netLiquidation ?? 0;
    message.equityWithLoan = object.equityWithLoan ?? 0;
    message.buyingPower = object.buyingPower ?? 0;
    message.cashBalance = object.cashBalance ?? 0;
    message.grossPositionValue = object.grossPositionValue ?? 0;
    message.initMarginReq = object.initMarginReq ?? 0;
    message.maintMarginReq = object.maintMarginReq ?? 0;
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
