// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: KlineData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface KlineData {
  /** bar timestamp. */
  time: number;
  /** The first transaction price of current minute. */
  open: number;
  /** The highest price of current minute. */
  high: number;
  /** The lowest price of current minute. */
  low: number;
  /** The last transaction price in the current minute */
  close: number;
  /** The average price of current minute. */
  avg: number;
  /** Cumulative trading volume in current minute. */
  volume: number;
  /** The number of transaction in current minute. */
  count: number;
  /** symbol */
  symbol: string;
  /** Cumulative turnover in current minute. */
  amount: number;
  serverTimestamp?: number | undefined;
}

function createBaseKlineData(): KlineData {
  return {
    time: 0,
    open: 0,
    high: 0,
    low: 0,
    close: 0,
    avg: 0,
    volume: 0,
    count: 0,
    symbol: "",
    amount: 0,
    serverTimestamp: undefined,
  };
}

export const KlineData: MessageFns<KlineData> = {
  encode(message: KlineData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.time !== 0) {
      writer.uint32(8).int64(message.time);
    }
    if (message.open !== 0) {
      writer.uint32(21).float(message.open);
    }
    if (message.high !== 0) {
      writer.uint32(29).float(message.high);
    }
    if (message.low !== 0) {
      writer.uint32(37).float(message.low);
    }
    if (message.close !== 0) {
      writer.uint32(45).float(message.close);
    }
    if (message.avg !== 0) {
      writer.uint32(53).float(message.avg);
    }
    if (message.volume !== 0) {
      writer.uint32(56).int64(message.volume);
    }
    if (message.count !== 0) {
      writer.uint32(64).int32(message.count);
    }
    if (message.symbol !== "") {
      writer.uint32(74).string(message.symbol);
    }
    if (message.amount !== 0) {
      writer.uint32(81).double(message.amount);
    }
    if (message.serverTimestamp !== undefined) {
      writer.uint32(88).uint64(message.serverTimestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KlineData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKlineData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.time = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.open = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.high = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.low = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.close = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.avg = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.volume = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.count = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 81) {
            break;
          }

          message.amount = reader.double();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.serverTimestamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<KlineData>, I>>(base?: I): KlineData {
    return KlineData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KlineData>, I>>(object: I): KlineData {
    const message = createBaseKlineData();
    message.time = object.time ?? 0;
    message.open = object.open ?? 0;
    message.high = object.high ?? 0;
    message.low = object.low ?? 0;
    message.close = object.close ?? 0;
    message.avg = object.avg ?? 0;
    message.volume = object.volume ?? 0;
    message.count = object.count ?? 0;
    message.symbol = object.symbol ?? "";
    message.amount = object.amount ?? 0;
    message.serverTimestamp = object.serverTimestamp ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
