// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: OptionTopData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface OptionTopData {
  market: string;
  timestamp: number;
  topData: OptionTopData_TopData[];
}

export interface OptionTopData_TopData {
  /** bigOrder, volume, amount, openInt */
  targetName: string;
  /** large order(bigOrder) */
  bigOrder: OptionTopData_BigOrder[];
  /** target value top list(volume, amount, openInt) */
  item: OptionTopData_OptionItem[];
}

export interface OptionTopData_BigOrder {
  symbol: string;
  /** formate:yyyyMMdd */
  expiry: string;
  /** strike price */
  strike: string;
  /** CALL/PUT */
  right: string;
  /** BUY/SELL */
  dir: string;
  /** target value: volume > 1000 */
  volume: number;
  /** trade price */
  price: number;
  /** trade amount */
  amount: number;
  /** trade timestamp */
  tradeTime: number;
}

export interface OptionTopData_OptionItem {
  symbol: string;
  /** formate:yyyyMMdd */
  expiry: string;
  /** strike price */
  strike: string;
  /** CALL/PUT */
  right: string;
  /** total trade amount */
  totalAmount: number;
  /** total trade volume */
  totalVolume: number;
  /** open interest */
  totalOpenInt: number;
  /** Volume to Open Interest */
  volumeToOpenInt: number;
  /** option latest price */
  latestPrice: number;
  /** uptate timestamp */
  updateTime: number;
}

function createBaseOptionTopData(): OptionTopData {
  return { market: "", timestamp: 0, topData: [] };
}

export const OptionTopData: MessageFns<OptionTopData> = {
  encode(message: OptionTopData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.market !== "") {
      writer.uint32(10).string(message.market);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    for (const v of message.topData) {
      OptionTopData_TopData.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OptionTopData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOptionTopData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.market = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.topData.push(OptionTopData_TopData.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OptionTopData>, I>>(base?: I): OptionTopData {
    return OptionTopData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OptionTopData>, I>>(object: I): OptionTopData {
    const message = createBaseOptionTopData();
    message.market = object.market ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.topData = object.topData?.map((e) => OptionTopData_TopData.fromPartial(e)) || [];
    return message;
  },
};

function createBaseOptionTopData_TopData(): OptionTopData_TopData {
  return { targetName: "", bigOrder: [], item: [] };
}

export const OptionTopData_TopData: MessageFns<OptionTopData_TopData> = {
  encode(message: OptionTopData_TopData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetName !== "") {
      writer.uint32(10).string(message.targetName);
    }
    for (const v of message.bigOrder) {
      OptionTopData_BigOrder.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.item) {
      OptionTopData_OptionItem.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OptionTopData_TopData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOptionTopData_TopData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bigOrder.push(OptionTopData_BigOrder.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.item.push(OptionTopData_OptionItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OptionTopData_TopData>, I>>(base?: I): OptionTopData_TopData {
    return OptionTopData_TopData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OptionTopData_TopData>, I>>(object: I): OptionTopData_TopData {
    const message = createBaseOptionTopData_TopData();
    message.targetName = object.targetName ?? "";
    message.bigOrder = object.bigOrder?.map((e) => OptionTopData_BigOrder.fromPartial(e)) || [];
    message.item = object.item?.map((e) => OptionTopData_OptionItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseOptionTopData_BigOrder(): OptionTopData_BigOrder {
  return { symbol: "", expiry: "", strike: "", right: "", dir: "", volume: 0, price: 0, amount: 0, tradeTime: 0 };
}

export const OptionTopData_BigOrder: MessageFns<OptionTopData_BigOrder> = {
  encode(message: OptionTopData_BigOrder, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.expiry !== "") {
      writer.uint32(18).string(message.expiry);
    }
    if (message.strike !== "") {
      writer.uint32(26).string(message.strike);
    }
    if (message.right !== "") {
      writer.uint32(34).string(message.right);
    }
    if (message.dir !== "") {
      writer.uint32(42).string(message.dir);
    }
    if (message.volume !== 0) {
      writer.uint32(49).double(message.volume);
    }
    if (message.price !== 0) {
      writer.uint32(57).double(message.price);
    }
    if (message.amount !== 0) {
      writer.uint32(65).double(message.amount);
    }
    if (message.tradeTime !== 0) {
      writer.uint32(72).int64(message.tradeTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OptionTopData_BigOrder {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOptionTopData_BigOrder();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.expiry = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.strike = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.right = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.dir = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.volume = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.price = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.amount = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.tradeTime = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OptionTopData_BigOrder>, I>>(base?: I): OptionTopData_BigOrder {
    return OptionTopData_BigOrder.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OptionTopData_BigOrder>, I>>(object: I): OptionTopData_BigOrder {
    const message = createBaseOptionTopData_BigOrder();
    message.symbol = object.symbol ?? "";
    message.expiry = object.expiry ?? "";
    message.strike = object.strike ?? "";
    message.right = object.right ?? "";
    message.dir = object.dir ?? "";
    message.volume = object.volume ?? 0;
    message.price = object.price ?? 0;
    message.amount = object.amount ?? 0;
    message.tradeTime = object.tradeTime ?? 0;
    return message;
  },
};

function createBaseOptionTopData_OptionItem(): OptionTopData_OptionItem {
  return {
    symbol: "",
    expiry: "",
    strike: "",
    right: "",
    totalAmount: 0,
    totalVolume: 0,
    totalOpenInt: 0,
    volumeToOpenInt: 0,
    latestPrice: 0,
    updateTime: 0,
  };
}

export const OptionTopData_OptionItem: MessageFns<OptionTopData_OptionItem> = {
  encode(message: OptionTopData_OptionItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.expiry !== "") {
      writer.uint32(18).string(message.expiry);
    }
    if (message.strike !== "") {
      writer.uint32(26).string(message.strike);
    }
    if (message.right !== "") {
      writer.uint32(34).string(message.right);
    }
    if (message.totalAmount !== 0) {
      writer.uint32(41).double(message.totalAmount);
    }
    if (message.totalVolume !== 0) {
      writer.uint32(49).double(message.totalVolume);
    }
    if (message.totalOpenInt !== 0) {
      writer.uint32(57).double(message.totalOpenInt);
    }
    if (message.volumeToOpenInt !== 0) {
      writer.uint32(65).double(message.volumeToOpenInt);
    }
    if (message.latestPrice !== 0) {
      writer.uint32(73).double(message.latestPrice);
    }
    if (message.updateTime !== 0) {
      writer.uint32(80).int64(message.updateTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OptionTopData_OptionItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOptionTopData_OptionItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.expiry = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.strike = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.right = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.totalAmount = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.totalVolume = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.totalOpenInt = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.volumeToOpenInt = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 73) {
            break;
          }

          message.latestPrice = reader.double();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.updateTime = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OptionTopData_OptionItem>, I>>(base?: I): OptionTopData_OptionItem {
    return OptionTopData_OptionItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OptionTopData_OptionItem>, I>>(object: I): OptionTopData_OptionItem {
    const message = createBaseOptionTopData_OptionItem();
    message.symbol = object.symbol ?? "";
    message.expiry = object.expiry ?? "";
    message.strike = object.strike ?? "";
    message.right = object.right ?? "";
    message.totalAmount = object.totalAmount ?? 0;
    message.totalVolume = object.totalVolume ?? 0;
    message.totalOpenInt = object.totalOpenInt ?? 0;
    message.volumeToOpenInt = object.volumeToOpenInt ?? 0;
    message.latestPrice = object.latestPrice ?? 0;
    message.updateTime = object.updateTime ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
