// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: OrderTransactionData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface OrderTransactionData {
  /** transact id */
  id: number;
  /** unique order id */
  orderId: number;
  /** user account */
  account: string;
  symbol: string;
  identifier: string;
  /** multiplier for futures, options, warrants and CBBC */
  multiplier: number;
  /** BUY or SELL */
  action: string;
  /** market. US, HK, etc. */
  market: string;
  /** currency. USD, HKD, etc. */
  currency: string;
  /** Securities Category C: (Commodities Futures), S: (Securities Stocks) */
  segType: string;
  /** STK Stocks, OPT Options, WAR Warrants, IOPT CBBC, CASH FOREX, FUT Futures, FOP Future Options */
  secType: string;
  /** filled price */
  filledPrice: number;
  /** filled quantity */
  filledQuantity: number;
  createTime: number;
  updateTime: number;
  /** transact time */
  transactTime: number;
  timestamp: number;
}

function createBaseOrderTransactionData(): OrderTransactionData {
  return {
    id: 0,
    orderId: 0,
    account: "",
    symbol: "",
    identifier: "",
    multiplier: 0,
    action: "",
    market: "",
    currency: "",
    segType: "",
    secType: "",
    filledPrice: 0,
    filledQuantity: 0,
    createTime: 0,
    updateTime: 0,
    transactTime: 0,
    timestamp: 0,
  };
}

export const OrderTransactionData: MessageFns<OrderTransactionData> = {
  encode(message: OrderTransactionData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).sint64(message.id);
    }
    if (message.orderId !== 0) {
      writer.uint32(16).sint64(message.orderId);
    }
    if (message.account !== "") {
      writer.uint32(26).string(message.account);
    }
    if (message.symbol !== "") {
      writer.uint32(34).string(message.symbol);
    }
    if (message.identifier !== "") {
      writer.uint32(42).string(message.identifier);
    }
    if (message.multiplier !== 0) {
      writer.uint32(48).uint32(message.multiplier);
    }
    if (message.action !== "") {
      writer.uint32(58).string(message.action);
    }
    if (message.market !== "") {
      writer.uint32(66).string(message.market);
    }
    if (message.currency !== "") {
      writer.uint32(74).string(message.currency);
    }
    if (message.segType !== "") {
      writer.uint32(82).string(message.segType);
    }
    if (message.secType !== "") {
      writer.uint32(90).string(message.secType);
    }
    if (message.filledPrice !== 0) {
      writer.uint32(97).double(message.filledPrice);
    }
    if (message.filledQuantity !== 0) {
      writer.uint32(104).sint64(message.filledQuantity);
    }
    if (message.createTime !== 0) {
      writer.uint32(112).uint64(message.createTime);
    }
    if (message.updateTime !== 0) {
      writer.uint32(120).uint64(message.updateTime);
    }
    if (message.transactTime !== 0) {
      writer.uint32(128).uint64(message.transactTime);
    }
    if (message.timestamp !== 0) {
      writer.uint32(136).uint64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderTransactionData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderTransactionData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.sint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.orderId = longToNumber(reader.sint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.account = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.identifier = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.multiplier = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.market = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.segType = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.secType = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 97) {
            break;
          }

          message.filledPrice = reader.double();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.filledQuantity = longToNumber(reader.sint64());
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.createTime = longToNumber(reader.uint64());
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.updateTime = longToNumber(reader.uint64());
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.transactTime = longToNumber(reader.uint64());
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OrderTransactionData>, I>>(base?: I): OrderTransactionData {
    return OrderTransactionData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderTransactionData>, I>>(object: I): OrderTransactionData {
    const message = createBaseOrderTransactionData();
    message.id = object.id ?? 0;
    message.orderId = object.orderId ?? 0;
    message.account = object.account ?? "";
    message.symbol = object.symbol ?? "";
    message.identifier = object.identifier ?? "";
    message.multiplier = object.multiplier ?? 0;
    message.action = object.action ?? "";
    message.market = object.market ?? "";
    message.currency = object.currency ?? "";
    message.segType = object.segType ?? "";
    message.secType = object.secType ?? "";
    message.filledPrice = object.filledPrice ?? 0;
    message.filledQuantity = object.filledQuantity ?? 0;
    message.createTime = object.createTime ?? 0;
    message.updateTime = object.updateTime ?? 0;
    message.transactTime = object.transactTime ?? 0;
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
