// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: OrderStatusData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface OrderStatusData {
  /** unique order id */
  id: number;
  /** user account */
  account: string;
  symbol: string;
  /** for options, formate:yyyyMMdd */
  expiry: string;
  /** for options */
  strike: string;
  /** for options */
  right: string;
  identifier: string;
  /** multiplier for futures, options, warrants and CBBC */
  multiplier: number;
  /** BUY or SELL */
  action: string;
  /** market. US, HK, etc. */
  market: string;
  /** currency. USD, HKD, etc. */
  currency: string;
  /** Securities Category C: (Commodities Futures), S: (Securities Stocks) */
  segType: string;
  /** STK Stocks, OPT Options, WAR Warrants, IOPT CBBC, CASH FOREX, FUT Futures, FOP Future Options */
  secType: string;
  /** order type */
  orderType: string;
  isLong: boolean;
  /** total quantity */
  totalQuantity: number;
  /** total quantity scale */
  totalQuantityScale: number;
  /** filled quantity */
  filledQuantity: number;
  /** filled quantity scale */
  filledQuantityScale: number;
  /** average price at which the orders got filled */
  avgFillPrice: number;
  /** limit price（required when orderType is 'LMT'） */
  limitPrice: number;
  /** stop price（required when orderType is 'STP'） */
  stopPrice: number;
  /** realized profit and loss */
  realizedPnl: number;
  /** order status */
  status: string;
  /** order replace status */
  replaceStatus: string;
  /** order cancel status */
  cancelStatus: string;
  /** if trade outside regular trading hours (only applicable to U.S. market) */
  outsideRth: boolean;
  canModify: boolean;
  canCancel: boolean;
  liquidation: boolean;
  /** symbol name */
  name: string;
  /** order source(from 'OpenApi', or not) */
  source: string;
  /** error message */
  errorMsg: string;
  /** order description */
  attrDesc: string;
  /** commission and fee */
  commissionAndFee: number;
  /** timestamp when the order is placed */
  openTime: number;
  timestamp: number;
  userMark: string;
  totalCashAmount: number;
  filledCashAmount: number;
  /** Goods and Services Tax(TBSG only) */
  gst: number;
  attrList: string[];
  timeInForce: string;
}

function createBaseOrderStatusData(): OrderStatusData {
  return {
    id: 0,
    account: "",
    symbol: "",
    expiry: "",
    strike: "",
    right: "",
    identifier: "",
    multiplier: 0,
    action: "",
    market: "",
    currency: "",
    segType: "",
    secType: "",
    orderType: "",
    isLong: false,
    totalQuantity: 0,
    totalQuantityScale: 0,
    filledQuantity: 0,
    filledQuantityScale: 0,
    avgFillPrice: 0,
    limitPrice: 0,
    stopPrice: 0,
    realizedPnl: 0,
    status: "",
    replaceStatus: "",
    cancelStatus: "",
    outsideRth: false,
    canModify: false,
    canCancel: false,
    liquidation: false,
    name: "",
    source: "",
    errorMsg: "",
    attrDesc: "",
    commissionAndFee: 0,
    openTime: 0,
    timestamp: 0,
    userMark: "",
    totalCashAmount: 0,
    filledCashAmount: 0,
    gst: 0,
    attrList: [],
    timeInForce: "",
  };
}

export const OrderStatusData: MessageFns<OrderStatusData> = {
  encode(message: OrderStatusData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).sint64(message.id);
    }
    if (message.account !== "") {
      writer.uint32(18).string(message.account);
    }
    if (message.symbol !== "") {
      writer.uint32(26).string(message.symbol);
    }
    if (message.expiry !== "") {
      writer.uint32(34).string(message.expiry);
    }
    if (message.strike !== "") {
      writer.uint32(42).string(message.strike);
    }
    if (message.right !== "") {
      writer.uint32(50).string(message.right);
    }
    if (message.identifier !== "") {
      writer.uint32(58).string(message.identifier);
    }
    if (message.multiplier !== 0) {
      writer.uint32(64).uint32(message.multiplier);
    }
    if (message.action !== "") {
      writer.uint32(74).string(message.action);
    }
    if (message.market !== "") {
      writer.uint32(82).string(message.market);
    }
    if (message.currency !== "") {
      writer.uint32(90).string(message.currency);
    }
    if (message.segType !== "") {
      writer.uint32(98).string(message.segType);
    }
    if (message.secType !== "") {
      writer.uint32(106).string(message.secType);
    }
    if (message.orderType !== "") {
      writer.uint32(114).string(message.orderType);
    }
    if (message.isLong !== false) {
      writer.uint32(120).bool(message.isLong);
    }
    if (message.totalQuantity !== 0) {
      writer.uint32(128).sint64(message.totalQuantity);
    }
    if (message.totalQuantityScale !== 0) {
      writer.uint32(136).sint32(message.totalQuantityScale);
    }
    if (message.filledQuantity !== 0) {
      writer.uint32(144).sint64(message.filledQuantity);
    }
    if (message.filledQuantityScale !== 0) {
      writer.uint32(152).sint32(message.filledQuantityScale);
    }
    if (message.avgFillPrice !== 0) {
      writer.uint32(161).double(message.avgFillPrice);
    }
    if (message.limitPrice !== 0) {
      writer.uint32(169).double(message.limitPrice);
    }
    if (message.stopPrice !== 0) {
      writer.uint32(177).double(message.stopPrice);
    }
    if (message.realizedPnl !== 0) {
      writer.uint32(185).double(message.realizedPnl);
    }
    if (message.status !== "") {
      writer.uint32(194).string(message.status);
    }
    if (message.replaceStatus !== "") {
      writer.uint32(202).string(message.replaceStatus);
    }
    if (message.cancelStatus !== "") {
      writer.uint32(210).string(message.cancelStatus);
    }
    if (message.outsideRth !== false) {
      writer.uint32(216).bool(message.outsideRth);
    }
    if (message.canModify !== false) {
      writer.uint32(224).bool(message.canModify);
    }
    if (message.canCancel !== false) {
      writer.uint32(232).bool(message.canCancel);
    }
    if (message.liquidation !== false) {
      writer.uint32(240).bool(message.liquidation);
    }
    if (message.name !== "") {
      writer.uint32(250).string(message.name);
    }
    if (message.source !== "") {
      writer.uint32(258).string(message.source);
    }
    if (message.errorMsg !== "") {
      writer.uint32(266).string(message.errorMsg);
    }
    if (message.attrDesc !== "") {
      writer.uint32(274).string(message.attrDesc);
    }
    if (message.commissionAndFee !== 0) {
      writer.uint32(285).float(message.commissionAndFee);
    }
    if (message.openTime !== 0) {
      writer.uint32(288).uint64(message.openTime);
    }
    if (message.timestamp !== 0) {
      writer.uint32(296).uint64(message.timestamp);
    }
    if (message.userMark !== "") {
      writer.uint32(306).string(message.userMark);
    }
    if (message.totalCashAmount !== 0) {
      writer.uint32(313).double(message.totalCashAmount);
    }
    if (message.filledCashAmount !== 0) {
      writer.uint32(321).double(message.filledCashAmount);
    }
    if (message.gst !== 0) {
      writer.uint32(329).double(message.gst);
    }
    for (const v of message.attrList) {
      writer.uint32(338).string(v!);
    }
    if (message.timeInForce !== "") {
      writer.uint32(346).string(message.timeInForce);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderStatusData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderStatusData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.sint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.account = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.expiry = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.strike = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.right = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.identifier = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.multiplier = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.market = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.segType = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.secType = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.orderType = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.isLong = reader.bool();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.totalQuantity = longToNumber(reader.sint64());
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.totalQuantityScale = reader.sint32();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.filledQuantity = longToNumber(reader.sint64());
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.filledQuantityScale = reader.sint32();
          continue;
        }
        case 20: {
          if (tag !== 161) {
            break;
          }

          message.avgFillPrice = reader.double();
          continue;
        }
        case 21: {
          if (tag !== 169) {
            break;
          }

          message.limitPrice = reader.double();
          continue;
        }
        case 22: {
          if (tag !== 177) {
            break;
          }

          message.stopPrice = reader.double();
          continue;
        }
        case 23: {
          if (tag !== 185) {
            break;
          }

          message.realizedPnl = reader.double();
          continue;
        }
        case 24: {
          if (tag !== 194) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 25: {
          if (tag !== 202) {
            break;
          }

          message.replaceStatus = reader.string();
          continue;
        }
        case 26: {
          if (tag !== 210) {
            break;
          }

          message.cancelStatus = reader.string();
          continue;
        }
        case 27: {
          if (tag !== 216) {
            break;
          }

          message.outsideRth = reader.bool();
          continue;
        }
        case 28: {
          if (tag !== 224) {
            break;
          }

          message.canModify = reader.bool();
          continue;
        }
        case 29: {
          if (tag !== 232) {
            break;
          }

          message.canCancel = reader.bool();
          continue;
        }
        case 30: {
          if (tag !== 240) {
            break;
          }

          message.liquidation = reader.bool();
          continue;
        }
        case 31: {
          if (tag !== 250) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 32: {
          if (tag !== 258) {
            break;
          }

          message.source = reader.string();
          continue;
        }
        case 33: {
          if (tag !== 266) {
            break;
          }

          message.errorMsg = reader.string();
          continue;
        }
        case 34: {
          if (tag !== 274) {
            break;
          }

          message.attrDesc = reader.string();
          continue;
        }
        case 35: {
          if (tag !== 285) {
            break;
          }

          message.commissionAndFee = reader.float();
          continue;
        }
        case 36: {
          if (tag !== 288) {
            break;
          }

          message.openTime = longToNumber(reader.uint64());
          continue;
        }
        case 37: {
          if (tag !== 296) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
        case 38: {
          if (tag !== 306) {
            break;
          }

          message.userMark = reader.string();
          continue;
        }
        case 39: {
          if (tag !== 313) {
            break;
          }

          message.totalCashAmount = reader.double();
          continue;
        }
        case 40: {
          if (tag !== 321) {
            break;
          }

          message.filledCashAmount = reader.double();
          continue;
        }
        case 41: {
          if (tag !== 329) {
            break;
          }

          message.gst = reader.double();
          continue;
        }
        case 42: {
          if (tag !== 338) {
            break;
          }

          message.attrList.push(reader.string());
          continue;
        }
        case 43: {
          if (tag !== 346) {
            break;
          }

          message.timeInForce = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OrderStatusData>, I>>(base?: I): OrderStatusData {
    return OrderStatusData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderStatusData>, I>>(object: I): OrderStatusData {
    const message = createBaseOrderStatusData();
    message.id = object.id ?? 0;
    message.account = object.account ?? "";
    message.symbol = object.symbol ?? "";
    message.expiry = object.expiry ?? "";
    message.strike = object.strike ?? "";
    message.right = object.right ?? "";
    message.identifier = object.identifier ?? "";
    message.multiplier = object.multiplier ?? 0;
    message.action = object.action ?? "";
    message.market = object.market ?? "";
    message.currency = object.currency ?? "";
    message.segType = object.segType ?? "";
    message.secType = object.secType ?? "";
    message.orderType = object.orderType ?? "";
    message.isLong = object.isLong ?? false;
    message.totalQuantity = object.totalQuantity ?? 0;
    message.totalQuantityScale = object.totalQuantityScale ?? 0;
    message.filledQuantity = object.filledQuantity ?? 0;
    message.filledQuantityScale = object.filledQuantityScale ?? 0;
    message.avgFillPrice = object.avgFillPrice ?? 0;
    message.limitPrice = object.limitPrice ?? 0;
    message.stopPrice = object.stopPrice ?? 0;
    message.realizedPnl = object.realizedPnl ?? 0;
    message.status = object.status ?? "";
    message.replaceStatus = object.replaceStatus ?? "";
    message.cancelStatus = object.cancelStatus ?? "";
    message.outsideRth = object.outsideRth ?? false;
    message.canModify = object.canModify ?? false;
    message.canCancel = object.canCancel ?? false;
    message.liquidation = object.liquidation ?? false;
    message.name = object.name ?? "";
    message.source = object.source ?? "";
    message.errorMsg = object.errorMsg ?? "";
    message.attrDesc = object.attrDesc ?? "";
    message.commissionAndFee = object.commissionAndFee ?? 0;
    message.openTime = object.openTime ?? 0;
    message.timestamp = object.timestamp ?? 0;
    message.userMark = object.userMark ?? "";
    message.totalCashAmount = object.totalCashAmount ?? 0;
    message.filledCashAmount = object.filledCashAmount ?? 0;
    message.gst = object.gst ?? 0;
    message.attrList = object.attrList?.map((e) => e) || [];
    message.timeInForce = object.timeInForce ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
