// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: PositionData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface PositionData {
  /** user account */
  account: string;
  symbol: string;
  /** for options */
  expiry: string;
  /** for options */
  strike: string;
  /** for options */
  right: string;
  identifier: string;
  /** multiplier for futures, options, warrants and CBBC */
  multiplier: number;
  /** market. US, HK, etc. */
  market: string;
  /** currency. USD, HKD, etc. */
  currency: string;
  /** Securities Category C: (Commodities Futures), S: (Securities Stocks) */
  segType: string;
  /** STK Stocks, OPT Options, WAR Warrants, IOPT CBBC, CASH FOREX, FUT Futures, FOP Future Options */
  secType: string;
  /** total position */
  position: number;
  /** total position scale */
  positionScale: number;
  /** average holding cost */
  averageCost: number;
  /** last price of the asset */
  latestPrice: number;
  /** market value of the asset */
  marketValue: number;
  /** unrealized profit and loss */
  unrealizedPnl: number;
  /** symbol name */
  name: string;
  timestamp: number;
  /** saleable quantity for Chinese A-share market stocks */
  saleable?:
    | number
    | undefined;
  /** total position quantity */
  positionQty: number;
  /** saleable quantity */
  salableQty: number;
}

function createBasePositionData(): PositionData {
  return {
    account: "",
    symbol: "",
    expiry: "",
    strike: "",
    right: "",
    identifier: "",
    multiplier: 0,
    market: "",
    currency: "",
    segType: "",
    secType: "",
    position: 0,
    positionScale: 0,
    averageCost: 0,
    latestPrice: 0,
    marketValue: 0,
    unrealizedPnl: 0,
    name: "",
    timestamp: 0,
    saleable: undefined,
    positionQty: 0,
    salableQty: 0,
  };
}

export const PositionData: MessageFns<PositionData> = {
  encode(message: PositionData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.account !== "") {
      writer.uint32(10).string(message.account);
    }
    if (message.symbol !== "") {
      writer.uint32(18).string(message.symbol);
    }
    if (message.expiry !== "") {
      writer.uint32(26).string(message.expiry);
    }
    if (message.strike !== "") {
      writer.uint32(34).string(message.strike);
    }
    if (message.right !== "") {
      writer.uint32(42).string(message.right);
    }
    if (message.identifier !== "") {
      writer.uint32(50).string(message.identifier);
    }
    if (message.multiplier !== 0) {
      writer.uint32(56).uint32(message.multiplier);
    }
    if (message.market !== "") {
      writer.uint32(66).string(message.market);
    }
    if (message.currency !== "") {
      writer.uint32(74).string(message.currency);
    }
    if (message.segType !== "") {
      writer.uint32(82).string(message.segType);
    }
    if (message.secType !== "") {
      writer.uint32(90).string(message.secType);
    }
    if (message.position !== 0) {
      writer.uint32(96).sint64(message.position);
    }
    if (message.positionScale !== 0) {
      writer.uint32(104).sint32(message.positionScale);
    }
    if (message.averageCost !== 0) {
      writer.uint32(113).double(message.averageCost);
    }
    if (message.latestPrice !== 0) {
      writer.uint32(121).double(message.latestPrice);
    }
    if (message.marketValue !== 0) {
      writer.uint32(129).double(message.marketValue);
    }
    if (message.unrealizedPnl !== 0) {
      writer.uint32(137).double(message.unrealizedPnl);
    }
    if (message.name !== "") {
      writer.uint32(146).string(message.name);
    }
    if (message.timestamp !== 0) {
      writer.uint32(152).uint64(message.timestamp);
    }
    if (message.saleable !== undefined) {
      writer.uint32(160).sint64(message.saleable);
    }
    if (message.positionQty !== 0) {
      writer.uint32(169).double(message.positionQty);
    }
    if (message.salableQty !== 0) {
      writer.uint32(177).double(message.salableQty);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PositionData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePositionData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.account = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.expiry = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.strike = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.right = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.identifier = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.multiplier = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.market = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.segType = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.secType = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.position = longToNumber(reader.sint64());
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.positionScale = reader.sint32();
          continue;
        }
        case 14: {
          if (tag !== 113) {
            break;
          }

          message.averageCost = reader.double();
          continue;
        }
        case 15: {
          if (tag !== 121) {
            break;
          }

          message.latestPrice = reader.double();
          continue;
        }
        case 16: {
          if (tag !== 129) {
            break;
          }

          message.marketValue = reader.double();
          continue;
        }
        case 17: {
          if (tag !== 137) {
            break;
          }

          message.unrealizedPnl = reader.double();
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.saleable = longToNumber(reader.sint64());
          continue;
        }
        case 21: {
          if (tag !== 169) {
            break;
          }

          message.positionQty = reader.double();
          continue;
        }
        case 22: {
          if (tag !== 177) {
            break;
          }

          message.salableQty = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PositionData>, I>>(base?: I): PositionData {
    return PositionData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PositionData>, I>>(object: I): PositionData {
    const message = createBasePositionData();
    message.account = object.account ?? "";
    message.symbol = object.symbol ?? "";
    message.expiry = object.expiry ?? "";
    message.strike = object.strike ?? "";
    message.right = object.right ?? "";
    message.identifier = object.identifier ?? "";
    message.multiplier = object.multiplier ?? 0;
    message.market = object.market ?? "";
    message.currency = object.currency ?? "";
    message.segType = object.segType ?? "";
    message.secType = object.secType ?? "";
    message.position = object.position ?? 0;
    message.positionScale = object.positionScale ?? 0;
    message.averageCost = object.averageCost ?? 0;
    message.latestPrice = object.latestPrice ?? 0;
    message.marketValue = object.marketValue ?? 0;
    message.unrealizedPnl = object.unrealizedPnl ?? 0;
    message.name = object.name ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.saleable = object.saleable ?? undefined;
    message.positionQty = object.positionQty ?? 0;
    message.salableQty = object.salableQty ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
