// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: PushData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AssetData } from "./AssetData";
import { KlineData } from "./KlineData";
import { OptionTopData } from "./OptionTopData";
import { OrderStatusData } from "./OrderStatusData";
import { OrderTransactionData } from "./OrderTransactionData";
import { PositionData } from "./PositionData";
import { QuoteData } from "./QuoteData";
import { QuoteDepthData } from "./QuoteDepthData";
import { SocketCommon_DataType } from "./SocketCommon";
import { StockTopData } from "./StockTopData";
import { TickData } from "./TickData";
import { TradeTickData } from "./TradeTickData";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface PushData {
  dataType: SocketCommon_DataType;
  quoteData?: QuoteData | undefined;
  quoteDepthData?: QuoteDepthData | undefined;
  tradeTickData?: TradeTickData | undefined;
  positionData?: PositionData | undefined;
  assetData?: AssetData | undefined;
  orderStatusData?: OrderStatusData | undefined;
  orderTransactionData?: OrderTransactionData | undefined;
  stockTopData?: StockTopData | undefined;
  optionTopData?: OptionTopData | undefined;
  klineData?: KlineData | undefined;
  tickData?: TickData | undefined;
}

function createBasePushData(): PushData {
  return {
    dataType: 0,
    quoteData: undefined,
    quoteDepthData: undefined,
    tradeTickData: undefined,
    positionData: undefined,
    assetData: undefined,
    orderStatusData: undefined,
    orderTransactionData: undefined,
    stockTopData: undefined,
    optionTopData: undefined,
    klineData: undefined,
    tickData: undefined,
  };
}

export const PushData: MessageFns<PushData> = {
  encode(message: PushData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dataType !== 0) {
      writer.uint32(8).int32(message.dataType);
    }
    if (message.quoteData !== undefined) {
      QuoteData.encode(message.quoteData, writer.uint32(18).fork()).join();
    }
    if (message.quoteDepthData !== undefined) {
      QuoteDepthData.encode(message.quoteDepthData, writer.uint32(26).fork()).join();
    }
    if (message.tradeTickData !== undefined) {
      TradeTickData.encode(message.tradeTickData, writer.uint32(34).fork()).join();
    }
    if (message.positionData !== undefined) {
      PositionData.encode(message.positionData, writer.uint32(42).fork()).join();
    }
    if (message.assetData !== undefined) {
      AssetData.encode(message.assetData, writer.uint32(50).fork()).join();
    }
    if (message.orderStatusData !== undefined) {
      OrderStatusData.encode(message.orderStatusData, writer.uint32(58).fork()).join();
    }
    if (message.orderTransactionData !== undefined) {
      OrderTransactionData.encode(message.orderTransactionData, writer.uint32(66).fork()).join();
    }
    if (message.stockTopData !== undefined) {
      StockTopData.encode(message.stockTopData, writer.uint32(74).fork()).join();
    }
    if (message.optionTopData !== undefined) {
      OptionTopData.encode(message.optionTopData, writer.uint32(82).fork()).join();
    }
    if (message.klineData !== undefined) {
      KlineData.encode(message.klineData, writer.uint32(90).fork()).join();
    }
    if (message.tickData !== undefined) {
      TickData.encode(message.tickData, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PushData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePushData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.dataType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.quoteData = QuoteData.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.quoteDepthData = QuoteDepthData.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.tradeTickData = TradeTickData.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.positionData = PositionData.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.assetData = AssetData.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.orderStatusData = OrderStatusData.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.orderTransactionData = OrderTransactionData.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.stockTopData = StockTopData.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.optionTopData = OptionTopData.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.klineData = KlineData.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.tickData = TickData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PushData>, I>>(base?: I): PushData {
    return PushData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PushData>, I>>(object: I): PushData {
    const message = createBasePushData();
    message.dataType = object.dataType ?? 0;
    message.quoteData = (object.quoteData !== undefined && object.quoteData !== null)
      ? QuoteData.fromPartial(object.quoteData)
      : undefined;
    message.quoteDepthData = (object.quoteDepthData !== undefined && object.quoteDepthData !== null)
      ? QuoteDepthData.fromPartial(object.quoteDepthData)
      : undefined;
    message.tradeTickData = (object.tradeTickData !== undefined && object.tradeTickData !== null)
      ? TradeTickData.fromPartial(object.tradeTickData)
      : undefined;
    message.positionData = (object.positionData !== undefined && object.positionData !== null)
      ? PositionData.fromPartial(object.positionData)
      : undefined;
    message.assetData = (object.assetData !== undefined && object.assetData !== null)
      ? AssetData.fromPartial(object.assetData)
      : undefined;
    message.orderStatusData = (object.orderStatusData !== undefined && object.orderStatusData !== null)
      ? OrderStatusData.fromPartial(object.orderStatusData)
      : undefined;
    message.orderTransactionData = (object.orderTransactionData !== undefined && object.orderTransactionData !== null)
      ? OrderTransactionData.fromPartial(object.orderTransactionData)
      : undefined;
    message.stockTopData = (object.stockTopData !== undefined && object.stockTopData !== null)
      ? StockTopData.fromPartial(object.stockTopData)
      : undefined;
    message.optionTopData = (object.optionTopData !== undefined && object.optionTopData !== null)
      ? OptionTopData.fromPartial(object.optionTopData)
      : undefined;
    message.klineData = (object.klineData !== undefined && object.klineData !== null)
      ? KlineData.fromPartial(object.klineData)
      : undefined;
    message.tickData = (object.tickData !== undefined && object.tickData !== null)
      ? TickData.fromPartial(object.tickData)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
