// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: QuoteBasicData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { QuoteData_Minute } from "./QuoteData";
import { SocketCommon_QuoteType } from "./SocketCommon";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface QuoteBasicData {
  symbol: string;
  /** BASIC/BBO */
  type: SocketCommon_QuoteType;
  timestamp: number;
  serverTimestamp?:
    | number
    | undefined;
  /** Options data not support */
  avgPrice?:
    | number
    | undefined;
  /**  */
  latestPrice?:
    | number
    | undefined;
  /** Pre/Post-Mkt data not support */
  latestPriceTimestamp?:
    | number
    | undefined;
  /**  */
  latestTime?:
    | string
    | undefined;
  /**  */
  preClose?:
    | number
    | undefined;
  /**  */
  volume?:
    | number
    | undefined;
  /** Futures and Options data not support */
  amount?:
    | number
    | undefined;
  /** Pre/Post-Mkt data not support */
  open?:
    | number
    | undefined;
  /** Pre/Post-Mkt data not support */
  high?:
    | number
    | undefined;
  /** Pre/Post-Mkt data not support */
  low?:
    | number
    | undefined;
  /** Pre/Post-Mkt */
  hourTradingTag?: string | undefined;
  marketStatus?:
    | string
    | undefined;
  /** only Options support */
  identifier?:
    | string
    | undefined;
  /** open interest, only Options support */
  openInt?:
    | number
    | undefined;
  /** latest trad time, only Futures support */
  tradeTime?:
    | number
    | undefined;
  /** previous settlement price, only Futures support */
  preSettlement?:
    | number
    | undefined;
  /** min tick, only Futures support */
  minTick?:
    | number
    | undefined;
  /** minute data: price, average price, time, volume */
  mi?:
    | QuoteData_Minute
    | undefined;
  /** Decimal value encoded as a string to avoid precision loss */
  volumeDecimal?: number | undefined;
}

function createBaseQuoteBasicData(): QuoteBasicData {
  return {
    symbol: "",
    type: 0,
    timestamp: 0,
    serverTimestamp: undefined,
    avgPrice: undefined,
    latestPrice: undefined,
    latestPriceTimestamp: undefined,
    latestTime: undefined,
    preClose: undefined,
    volume: undefined,
    amount: undefined,
    open: undefined,
    high: undefined,
    low: undefined,
    hourTradingTag: undefined,
    marketStatus: undefined,
    identifier: undefined,
    openInt: undefined,
    tradeTime: undefined,
    preSettlement: undefined,
    minTick: undefined,
    mi: undefined,
    volumeDecimal: undefined,
  };
}

export const QuoteBasicData: MessageFns<QuoteBasicData> = {
  encode(message: QuoteBasicData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    if (message.timestamp !== 0) {
      writer.uint32(24).uint64(message.timestamp);
    }
    if (message.serverTimestamp !== undefined) {
      writer.uint32(32).uint64(message.serverTimestamp);
    }
    if (message.avgPrice !== undefined) {
      writer.uint32(41).double(message.avgPrice);
    }
    if (message.latestPrice !== undefined) {
      writer.uint32(49).double(message.latestPrice);
    }
    if (message.latestPriceTimestamp !== undefined) {
      writer.uint32(56).uint64(message.latestPriceTimestamp);
    }
    if (message.latestTime !== undefined) {
      writer.uint32(66).string(message.latestTime);
    }
    if (message.preClose !== undefined) {
      writer.uint32(73).double(message.preClose);
    }
    if (message.volume !== undefined) {
      writer.uint32(80).sint64(message.volume);
    }
    if (message.amount !== undefined) {
      writer.uint32(89).double(message.amount);
    }
    if (message.open !== undefined) {
      writer.uint32(97).double(message.open);
    }
    if (message.high !== undefined) {
      writer.uint32(105).double(message.high);
    }
    if (message.low !== undefined) {
      writer.uint32(113).double(message.low);
    }
    if (message.hourTradingTag !== undefined) {
      writer.uint32(122).string(message.hourTradingTag);
    }
    if (message.marketStatus !== undefined) {
      writer.uint32(130).string(message.marketStatus);
    }
    if (message.identifier !== undefined) {
      writer.uint32(186).string(message.identifier);
    }
    if (message.openInt !== undefined) {
      writer.uint32(192).sint64(message.openInt);
    }
    if (message.tradeTime !== undefined) {
      writer.uint32(200).uint64(message.tradeTime);
    }
    if (message.preSettlement !== undefined) {
      writer.uint32(209).double(message.preSettlement);
    }
    if (message.minTick !== undefined) {
      writer.uint32(221).float(message.minTick);
    }
    if (message.mi !== undefined) {
      QuoteData_Minute.encode(message.mi, writer.uint32(226).fork()).join();
    }
    if (message.volumeDecimal !== undefined) {
      writer.uint32(233).double(message.volumeDecimal);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuoteBasicData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuoteBasicData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.serverTimestamp = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.avgPrice = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.latestPrice = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.latestPriceTimestamp = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.latestTime = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 73) {
            break;
          }

          message.preClose = reader.double();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.volume = longToNumber(reader.sint64());
          continue;
        }
        case 11: {
          if (tag !== 89) {
            break;
          }

          message.amount = reader.double();
          continue;
        }
        case 12: {
          if (tag !== 97) {
            break;
          }

          message.open = reader.double();
          continue;
        }
        case 13: {
          if (tag !== 105) {
            break;
          }

          message.high = reader.double();
          continue;
        }
        case 14: {
          if (tag !== 113) {
            break;
          }

          message.low = reader.double();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.hourTradingTag = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.marketStatus = reader.string();
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.identifier = reader.string();
          continue;
        }
        case 24: {
          if (tag !== 192) {
            break;
          }

          message.openInt = longToNumber(reader.sint64());
          continue;
        }
        case 25: {
          if (tag !== 200) {
            break;
          }

          message.tradeTime = longToNumber(reader.uint64());
          continue;
        }
        case 26: {
          if (tag !== 209) {
            break;
          }

          message.preSettlement = reader.double();
          continue;
        }
        case 27: {
          if (tag !== 221) {
            break;
          }

          message.minTick = reader.float();
          continue;
        }
        case 28: {
          if (tag !== 226) {
            break;
          }

          message.mi = QuoteData_Minute.decode(reader, reader.uint32());
          continue;
        }
        case 29: {
          if (tag !== 233) {
            break;
          }

          message.volumeDecimal = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<QuoteBasicData>, I>>(base?: I): QuoteBasicData {
    return QuoteBasicData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuoteBasicData>, I>>(object: I): QuoteBasicData {
    const message = createBaseQuoteBasicData();
    message.symbol = object.symbol ?? "";
    message.type = object.type ?? 0;
    message.timestamp = object.timestamp ?? 0;
    message.serverTimestamp = object.serverTimestamp ?? undefined;
    message.avgPrice = object.avgPrice ?? undefined;
    message.latestPrice = object.latestPrice ?? undefined;
    message.latestPriceTimestamp = object.latestPriceTimestamp ?? undefined;
    message.latestTime = object.latestTime ?? undefined;
    message.preClose = object.preClose ?? undefined;
    message.volume = object.volume ?? undefined;
    message.amount = object.amount ?? undefined;
    message.open = object.open ?? undefined;
    message.high = object.high ?? undefined;
    message.low = object.low ?? undefined;
    message.hourTradingTag = object.hourTradingTag ?? undefined;
    message.marketStatus = object.marketStatus ?? undefined;
    message.identifier = object.identifier ?? undefined;
    message.openInt = object.openInt ?? undefined;
    message.tradeTime = object.tradeTime ?? undefined;
    message.preSettlement = object.preSettlement ?? undefined;
    message.minTick = object.minTick ?? undefined;
    message.mi = (object.mi !== undefined && object.mi !== null) ? QuoteData_Minute.fromPartial(object.mi) : undefined;
    message.volumeDecimal = object.volumeDecimal ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
