// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: QuoteDepthData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface QuoteDepthData {
  symbol: string;
  timestamp: number;
  ask: QuoteDepthData_OrderBook | undefined;
  bid: QuoteDepthData_OrderBook | undefined;
}

export interface QuoteDepthData_OrderBook {
  price: number[];
  volume: number[];
  /** required when symbol in HK market */
  orderCount: number[];
  /** option exchange */
  exchange: string[];
  /** option exchange time */
  time: number[];
}

function createBaseQuoteDepthData(): QuoteDepthData {
  return { symbol: "", timestamp: 0, ask: undefined, bid: undefined };
}

export const QuoteDepthData: MessageFns<QuoteDepthData> = {
  encode(message: QuoteDepthData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).uint64(message.timestamp);
    }
    if (message.ask !== undefined) {
      QuoteDepthData_OrderBook.encode(message.ask, writer.uint32(26).fork()).join();
    }
    if (message.bid !== undefined) {
      QuoteDepthData_OrderBook.encode(message.bid, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuoteDepthData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuoteDepthData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ask = QuoteDepthData_OrderBook.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.bid = QuoteDepthData_OrderBook.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<QuoteDepthData>, I>>(base?: I): QuoteDepthData {
    return QuoteDepthData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuoteDepthData>, I>>(object: I): QuoteDepthData {
    const message = createBaseQuoteDepthData();
    message.symbol = object.symbol ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.ask = (object.ask !== undefined && object.ask !== null)
      ? QuoteDepthData_OrderBook.fromPartial(object.ask)
      : undefined;
    message.bid = (object.bid !== undefined && object.bid !== null)
      ? QuoteDepthData_OrderBook.fromPartial(object.bid)
      : undefined;
    return message;
  },
};

function createBaseQuoteDepthData_OrderBook(): QuoteDepthData_OrderBook {
  return { price: [], volume: [], orderCount: [], exchange: [], time: [] };
}

export const QuoteDepthData_OrderBook: MessageFns<QuoteDepthData_OrderBook> = {
  encode(message: QuoteDepthData_OrderBook, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.price) {
      writer.double(v);
    }
    writer.join();
    writer.uint32(18).fork();
    for (const v of message.volume) {
      writer.sint64(v);
    }
    writer.join();
    writer.uint32(26).fork();
    for (const v of message.orderCount) {
      writer.uint32(v);
    }
    writer.join();
    for (const v of message.exchange) {
      writer.uint32(34).string(v!);
    }
    writer.uint32(42).fork();
    for (const v of message.time) {
      writer.sint64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuoteDepthData_OrderBook {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuoteDepthData_OrderBook();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 9) {
            message.price.push(reader.double());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.price.push(reader.double());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag === 16) {
            message.volume.push(longToNumber(reader.sint64()));

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.volume.push(longToNumber(reader.sint64()));
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag === 24) {
            message.orderCount.push(reader.uint32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.orderCount.push(reader.uint32());
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.exchange.push(reader.string());
          continue;
        }
        case 5: {
          if (tag === 40) {
            message.time.push(longToNumber(reader.sint64()));

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.time.push(longToNumber(reader.sint64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<QuoteDepthData_OrderBook>, I>>(base?: I): QuoteDepthData_OrderBook {
    return QuoteDepthData_OrderBook.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuoteDepthData_OrderBook>, I>>(object: I): QuoteDepthData_OrderBook {
    const message = createBaseQuoteDepthData_OrderBook();
    message.price = object.price?.map((e) => e) || [];
    message.volume = object.volume?.map((e) => e) || [];
    message.orderCount = object.orderCount?.map((e) => e) || [];
    message.exchange = object.exchange?.map((e) => e) || [];
    message.time = object.time?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
