// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: QuoteBBOData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SocketCommon_QuoteType } from "./SocketCommon";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface QuoteBBOData {
  symbol: string;
  /** BBO */
  type: SocketCommon_QuoteType;
  timestamp: number;
  askPrice: number;
  askSize: number;
  /** Pre/Post-Mkt data not support */
  askTimestamp?: number | undefined;
  bidPrice: number;
  bidSize: number;
  /** Pre/Post-Mkt data not support */
  bidTimestamp?: number | undefined;
}

function createBaseQuoteBBOData(): QuoteBBOData {
  return {
    symbol: "",
    type: 0,
    timestamp: 0,
    askPrice: 0,
    askSize: 0,
    askTimestamp: undefined,
    bidPrice: 0,
    bidSize: 0,
    bidTimestamp: undefined,
  };
}

export const QuoteBBOData: MessageFns<QuoteBBOData> = {
  encode(message: QuoteBBOData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    if (message.timestamp !== 0) {
      writer.uint32(24).uint64(message.timestamp);
    }
    if (message.askPrice !== 0) {
      writer.uint32(137).double(message.askPrice);
    }
    if (message.askSize !== 0) {
      writer.uint32(144).sint64(message.askSize);
    }
    if (message.askTimestamp !== undefined) {
      writer.uint32(152).uint64(message.askTimestamp);
    }
    if (message.bidPrice !== 0) {
      writer.uint32(161).double(message.bidPrice);
    }
    if (message.bidSize !== 0) {
      writer.uint32(168).sint64(message.bidSize);
    }
    if (message.bidTimestamp !== undefined) {
      writer.uint32(176).uint64(message.bidTimestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuoteBBOData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuoteBBOData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
        case 17: {
          if (tag !== 137) {
            break;
          }

          message.askPrice = reader.double();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.askSize = longToNumber(reader.sint64());
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.askTimestamp = longToNumber(reader.uint64());
          continue;
        }
        case 20: {
          if (tag !== 161) {
            break;
          }

          message.bidPrice = reader.double();
          continue;
        }
        case 21: {
          if (tag !== 168) {
            break;
          }

          message.bidSize = longToNumber(reader.sint64());
          continue;
        }
        case 22: {
          if (tag !== 176) {
            break;
          }

          message.bidTimestamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<QuoteBBOData>, I>>(base?: I): QuoteBBOData {
    return QuoteBBOData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuoteBBOData>, I>>(object: I): QuoteBBOData {
    const message = createBaseQuoteBBOData();
    message.symbol = object.symbol ?? "";
    message.type = object.type ?? 0;
    message.timestamp = object.timestamp ?? 0;
    message.askPrice = object.askPrice ?? 0;
    message.askSize = object.askSize ?? 0;
    message.askTimestamp = object.askTimestamp ?? undefined;
    message.bidPrice = object.bidPrice ?? 0;
    message.bidSize = object.bidSize ?? 0;
    message.bidTimestamp = object.bidTimestamp ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
