// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: Request.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SocketCommon_Command, SocketCommon_DataType } from "./SocketCommon";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface Request {
  command: SocketCommon_Command;
  id: number;
  subscribe?: Request_Subscribe | undefined;
  connect?: Request_Connect | undefined;
}

export interface Request_Connect {
  tigerId: string;
  sign: string;
  sdkVersion: string;
  acceptVersion?: string | undefined;
  sendInterval?: number | undefined;
  receiveInterval?: number | undefined;
  useFullTick?: boolean | undefined;
}

export interface Request_Subscribe {
  dataType: SocketCommon_DataType;
  symbols?: string | undefined;
  account?: string | undefined;
  market?: string | undefined;
}

function createBaseRequest(): Request {
  return { command: 0, id: 0, subscribe: undefined, connect: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.command !== 0) {
      writer.uint32(8).int32(message.command);
    }
    if (message.id !== 0) {
      writer.uint32(16).uint32(message.id);
    }
    if (message.subscribe !== undefined) {
      Request_Subscribe.encode(message.subscribe, writer.uint32(26).fork()).join();
    }
    if (message.connect !== undefined) {
      Request_Connect.encode(message.connect, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.command = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.subscribe = Request_Subscribe.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.connect = Request_Connect.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.command = object.command ?? 0;
    message.id = object.id ?? 0;
    message.subscribe = (object.subscribe !== undefined && object.subscribe !== null)
      ? Request_Subscribe.fromPartial(object.subscribe)
      : undefined;
    message.connect = (object.connect !== undefined && object.connect !== null)
      ? Request_Connect.fromPartial(object.connect)
      : undefined;
    return message;
  },
};

function createBaseRequest_Connect(): Request_Connect {
  return {
    tigerId: "",
    sign: "",
    sdkVersion: "",
    acceptVersion: undefined,
    sendInterval: undefined,
    receiveInterval: undefined,
    useFullTick: undefined,
  };
}

export const Request_Connect: MessageFns<Request_Connect> = {
  encode(message: Request_Connect, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tigerId !== "") {
      writer.uint32(10).string(message.tigerId);
    }
    if (message.sign !== "") {
      writer.uint32(18).string(message.sign);
    }
    if (message.sdkVersion !== "") {
      writer.uint32(26).string(message.sdkVersion);
    }
    if (message.acceptVersion !== undefined) {
      writer.uint32(34).string(message.acceptVersion);
    }
    if (message.sendInterval !== undefined) {
      writer.uint32(40).uint32(message.sendInterval);
    }
    if (message.receiveInterval !== undefined) {
      writer.uint32(48).uint32(message.receiveInterval);
    }
    if (message.useFullTick !== undefined) {
      writer.uint32(56).bool(message.useFullTick);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request_Connect {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest_Connect();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tigerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sign = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sdkVersion = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.acceptVersion = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.sendInterval = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.receiveInterval = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.useFullTick = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Request_Connect>, I>>(base?: I): Request_Connect {
    return Request_Connect.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request_Connect>, I>>(object: I): Request_Connect {
    const message = createBaseRequest_Connect();
    message.tigerId = object.tigerId ?? "";
    message.sign = object.sign ?? "";
    message.sdkVersion = object.sdkVersion ?? "";
    message.acceptVersion = object.acceptVersion ?? undefined;
    message.sendInterval = object.sendInterval ?? undefined;
    message.receiveInterval = object.receiveInterval ?? undefined;
    message.useFullTick = object.useFullTick ?? undefined;
    return message;
  },
};

function createBaseRequest_Subscribe(): Request_Subscribe {
  return { dataType: 0, symbols: undefined, account: undefined, market: undefined };
}

export const Request_Subscribe: MessageFns<Request_Subscribe> = {
  encode(message: Request_Subscribe, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dataType !== 0) {
      writer.uint32(8).int32(message.dataType);
    }
    if (message.symbols !== undefined) {
      writer.uint32(18).string(message.symbols);
    }
    if (message.account !== undefined) {
      writer.uint32(26).string(message.account);
    }
    if (message.market !== undefined) {
      writer.uint32(34).string(message.market);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request_Subscribe {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest_Subscribe();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.dataType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.symbols = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.account = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.market = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Request_Subscribe>, I>>(base?: I): Request_Subscribe {
    return Request_Subscribe.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request_Subscribe>, I>>(object: I): Request_Subscribe {
    const message = createBaseRequest_Subscribe();
    message.dataType = object.dataType ?? 0;
    message.symbols = object.symbols ?? undefined;
    message.account = object.account ?? undefined;
    message.market = object.market ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
