// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: SocketCommon.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface SocketCommon {
}

/** request and response command */
export enum SocketCommon_Command {
  UNKNOWN = 0,
  CONNECT = 1,
  CONNECTED = 2,
  SEND = 3,
  SUBSCRIBE = 4,
  UNSUBSCRIBE = 5,
  DISCONNECT = 6,
  MESSAGE = 7,
  HEARTBEAT = 8,
  ERROR = 9,
  UNRECOGNIZED = -1,
}

/** data type */
export enum SocketCommon_DataType {
  Unknown = 0,
  Quote = 1,
  Option = 2,
  Future = 3,
  QuoteDepth = 4,
  TradeTick = 5,
  Asset = 6,
  Position = 7,
  OrderStatus = 8,
  OrderTransaction = 9,
  StockTop = 10,
  OptionTop = 11,
  Kline = 12,
  Cc = 13,
  UNRECOGNIZED = -1,
}

export enum SocketCommon_QuoteType {
  None = 0,
  /** BASIC - basic quote data */
  BASIC = 1,
  /** BBO - best bid and offer(include fields: askSize,askPrice,bidSize,bizePrice) */
  BBO = 2,
  /** ALL - include BASIC AND BBO */
  ALL = 3,
  UNRECOGNIZED = -1,
}

function createBaseSocketCommon(): SocketCommon {
  return {};
}

export const SocketCommon: MessageFns<SocketCommon> = {
  encode(_: SocketCommon, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SocketCommon {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSocketCommon();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SocketCommon>, I>>(base?: I): SocketCommon {
    return SocketCommon.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SocketCommon>, I>>(_: I): SocketCommon {
    const message = createBaseSocketCommon();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
