// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: StockTopData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface StockTopData {
  market: string;
  timestamp: number;
  topData: StockTopData_TopData[];
}

export interface StockTopData_TopData {
  /** changeRate, changeRate5Min, turnoverRate, amount, volume, amplitude */
  targetName: string;
  item: StockTopData_StockItem[];
}

export interface StockTopData_StockItem {
  symbol: string;
  latestPrice: number;
  targetValue: number;
}

function createBaseStockTopData(): StockTopData {
  return { market: "", timestamp: 0, topData: [] };
}

export const StockTopData: MessageFns<StockTopData> = {
  encode(message: StockTopData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.market !== "") {
      writer.uint32(10).string(message.market);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    for (const v of message.topData) {
      StockTopData_TopData.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StockTopData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStockTopData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.market = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.topData.push(StockTopData_TopData.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StockTopData>, I>>(base?: I): StockTopData {
    return StockTopData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StockTopData>, I>>(object: I): StockTopData {
    const message = createBaseStockTopData();
    message.market = object.market ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.topData = object.topData?.map((e) => StockTopData_TopData.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStockTopData_TopData(): StockTopData_TopData {
  return { targetName: "", item: [] };
}

export const StockTopData_TopData: MessageFns<StockTopData_TopData> = {
  encode(message: StockTopData_TopData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetName !== "") {
      writer.uint32(10).string(message.targetName);
    }
    for (const v of message.item) {
      StockTopData_StockItem.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StockTopData_TopData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStockTopData_TopData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.item.push(StockTopData_StockItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StockTopData_TopData>, I>>(base?: I): StockTopData_TopData {
    return StockTopData_TopData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StockTopData_TopData>, I>>(object: I): StockTopData_TopData {
    const message = createBaseStockTopData_TopData();
    message.targetName = object.targetName ?? "";
    message.item = object.item?.map((e) => StockTopData_StockItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStockTopData_StockItem(): StockTopData_StockItem {
  return { symbol: "", latestPrice: 0, targetValue: 0 };
}

export const StockTopData_StockItem: MessageFns<StockTopData_StockItem> = {
  encode(message: StockTopData_StockItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.latestPrice !== 0) {
      writer.uint32(17).double(message.latestPrice);
    }
    if (message.targetValue !== 0) {
      writer.uint32(25).double(message.targetValue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StockTopData_StockItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStockTopData_StockItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.latestPrice = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.targetValue = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StockTopData_StockItem>, I>>(base?: I): StockTopData_StockItem {
    return StockTopData_StockItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StockTopData_StockItem>, I>>(object: I): StockTopData_StockItem {
    const message = createBaseStockTopData_StockItem();
    message.symbol = object.symbol ?? "";
    message.latestPrice = object.latestPrice ?? 0;
    message.targetValue = object.targetValue ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
