// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: TickData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface TickData {
  symbol: string;
  ticks: TickData_Tick[];
  timestamp: number;
  /** data source (Optional) */
  source: string;
}

export interface TickData_Tick {
  /** The order in which upstream data arrives, for reference only. */
  sn: number;
  /** Execution time of transaction. 13-digit timestamp */
  time: number;
  /** Transaction price. */
  price: number;
  /** Transaction volume. */
  volume: number;
  /** buy/sell direction. Active buy(+); Active sell(-); Neutral transaction(*) */
  type: string;
  /** The trade condition for irregular transaction. (Optional) */
  cond: string;
  /** The market participant reports the transaction. (Optional) */
  partCode: string;
}

function createBaseTickData(): TickData {
  return { symbol: "", ticks: [], timestamp: 0, source: "" };
}

export const TickData: MessageFns<TickData> = {
  encode(message: TickData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    for (const v of message.ticks) {
      TickData_Tick.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.timestamp !== 0) {
      writer.uint32(24).int64(message.timestamp);
    }
    if (message.source !== "") {
      writer.uint32(34).string(message.source);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TickData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTickData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ticks.push(TickData_Tick.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.source = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<TickData>, I>>(base?: I): TickData {
    return TickData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TickData>, I>>(object: I): TickData {
    const message = createBaseTickData();
    message.symbol = object.symbol ?? "";
    message.ticks = object.ticks?.map((e) => TickData_Tick.fromPartial(e)) || [];
    message.timestamp = object.timestamp ?? 0;
    message.source = object.source ?? "";
    return message;
  },
};

function createBaseTickData_Tick(): TickData_Tick {
  return { sn: 0, time: 0, price: 0, volume: 0, type: "", cond: "", partCode: "" };
}

export const TickData_Tick: MessageFns<TickData_Tick> = {
  encode(message: TickData_Tick, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sn !== 0) {
      writer.uint32(8).int64(message.sn);
    }
    if (message.time !== 0) {
      writer.uint32(16).int64(message.time);
    }
    if (message.price !== 0) {
      writer.uint32(29).float(message.price);
    }
    if (message.volume !== 0) {
      writer.uint32(32).int32(message.volume);
    }
    if (message.type !== "") {
      writer.uint32(42).string(message.type);
    }
    if (message.cond !== "") {
      writer.uint32(50).string(message.cond);
    }
    if (message.partCode !== "") {
      writer.uint32(58).string(message.partCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TickData_Tick {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTickData_Tick();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sn = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.time = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.price = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.volume = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.cond = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.partCode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<TickData_Tick>, I>>(base?: I): TickData_Tick {
    return TickData_Tick.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TickData_Tick>, I>>(object: I): TickData_Tick {
    const message = createBaseTickData_Tick();
    message.sn = object.sn ?? 0;
    message.time = object.time ?? 0;
    message.price = object.price ?? 0;
    message.volume = object.volume ?? 0;
    message.type = object.type ?? "";
    message.cond = object.cond ?? "";
    message.partCode = object.partCode ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
