// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.28.3
// source: TradeTickData.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.tigerbrokers.stock.openapi.client.socket.data.pb";

export interface TradeTickData {
  symbol: string;
  /** buy/sell direction. Active buy(+); Active sell(-); Neutral transaction(*).Futures are not supported */
  type: string;
  /** The trade condition for irregular transaction.(Futures are not supported) */
  cond: string;
  /** serial number */
  sn: number;
  priceBase: number;
  priceOffset: number;
  /** The compressed transaction time is restored to the original time: time[i] = time[i] + time[i-1] */
  time: number[];
  /** The compressed transaction price is restored to the original price: price[i] = (priceBase + price[i]) / 10^priceOffset */
  price: number[];
  /** volume */
  volume: number[];
  /** The market participant reports the transaction，Usually a ~ z characters.(Futures are not supported) */
  partCode: string[];
  /** (Futures are not supported) */
  quoteLevel: string;
  timestamp: number;
  /** STK Stocks, FUT Futures */
  secType: string;
  /** Original number of merges(Only futures are supported) */
  mergedVols: TradeTickData_MergedVol[];
}

export interface TradeTickData_MergedVol {
  /** Original number of merges */
  mergeTimes: number;
  /** original trading volume */
  vol: number[];
}

function createBaseTradeTickData(): TradeTickData {
  return {
    symbol: "",
    type: "",
    cond: "",
    sn: 0,
    priceBase: 0,
    priceOffset: 0,
    time: [],
    price: [],
    volume: [],
    partCode: [],
    quoteLevel: "",
    timestamp: 0,
    secType: "",
    mergedVols: [],
  };
}

export const TradeTickData: MessageFns<TradeTickData> = {
  encode(message: TradeTickData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.cond !== "") {
      writer.uint32(26).string(message.cond);
    }
    if (message.sn !== 0) {
      writer.uint32(32).int64(message.sn);
    }
    if (message.priceBase !== 0) {
      writer.uint32(40).int64(message.priceBase);
    }
    if (message.priceOffset !== 0) {
      writer.uint32(48).int32(message.priceOffset);
    }
    writer.uint32(58).fork();
    for (const v of message.time) {
      writer.int64(v);
    }
    writer.join();
    writer.uint32(66).fork();
    for (const v of message.price) {
      writer.int64(v);
    }
    writer.join();
    writer.uint32(74).fork();
    for (const v of message.volume) {
      writer.int64(v);
    }
    writer.join();
    for (const v of message.partCode) {
      writer.uint32(82).string(v!);
    }
    if (message.quoteLevel !== "") {
      writer.uint32(90).string(message.quoteLevel);
    }
    if (message.timestamp !== 0) {
      writer.uint32(96).uint64(message.timestamp);
    }
    if (message.secType !== "") {
      writer.uint32(106).string(message.secType);
    }
    for (const v of message.mergedVols) {
      TradeTickData_MergedVol.encode(v!, writer.uint32(114).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TradeTickData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTradeTickData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.cond = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.sn = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.priceBase = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.priceOffset = reader.int32();
          continue;
        }
        case 7: {
          if (tag === 56) {
            message.time.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.time.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
        case 8: {
          if (tag === 64) {
            message.price.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 66) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.price.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
        case 9: {
          if (tag === 72) {
            message.volume.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 74) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.volume.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.partCode.push(reader.string());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.quoteLevel = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.secType = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.mergedVols.push(TradeTickData_MergedVol.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<TradeTickData>, I>>(base?: I): TradeTickData {
    return TradeTickData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TradeTickData>, I>>(object: I): TradeTickData {
    const message = createBaseTradeTickData();
    message.symbol = object.symbol ?? "";
    message.type = object.type ?? "";
    message.cond = object.cond ?? "";
    message.sn = object.sn ?? 0;
    message.priceBase = object.priceBase ?? 0;
    message.priceOffset = object.priceOffset ?? 0;
    message.time = object.time?.map((e) => e) || [];
    message.price = object.price?.map((e) => e) || [];
    message.volume = object.volume?.map((e) => e) || [];
    message.partCode = object.partCode?.map((e) => e) || [];
    message.quoteLevel = object.quoteLevel ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.secType = object.secType ?? "";
    message.mergedVols = object.mergedVols?.map((e) => TradeTickData_MergedVol.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTradeTickData_MergedVol(): TradeTickData_MergedVol {
  return { mergeTimes: 0, vol: [] };
}

export const TradeTickData_MergedVol: MessageFns<TradeTickData_MergedVol> = {
  encode(message: TradeTickData_MergedVol, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mergeTimes !== 0) {
      writer.uint32(8).int32(message.mergeTimes);
    }
    writer.uint32(18).fork();
    for (const v of message.vol) {
      writer.int64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TradeTickData_MergedVol {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTradeTickData_MergedVol();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mergeTimes = reader.int32();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.vol.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.vol.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<TradeTickData_MergedVol>, I>>(base?: I): TradeTickData_MergedVol {
    return TradeTickData_MergedVol.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TradeTickData_MergedVol>, I>>(object: I): TradeTickData_MergedVol {
    const message = createBaseTradeTickData_MergedVol();
    message.mergeTimes = object.mergeTimes ?? 0;
    message.vol = object.vol?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
